#!/usr/bin/env python3
"""Run and evaluate real-time Phase 3 Demo windows without source changes."""

import concurrent.futures
import json
import os
import secrets
import socket
import subprocess
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from collections import Counter
from datetime import datetime, timedelta, timezone
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
BASE_COMPOSE = HERE / "compose.yaml"
OVERRIDE = HERE / "phase3.override.yaml"
EVIDENCE_DIR = HERE / "evidence"
API = os.environ.get("INCIDENTLENS_API_URL", "http://127.0.0.1:18081").rstrip("/")
DEMO = os.environ.get("INCIDENTLENS_DEMO_URL", "http://127.0.0.1:8080").rstrip("/")
RECOMMENDATIONS = "/api/recommendations?productIds=OLJCESPC7Z&productIds=OLJCESPC7Z"
UNKNOWN_PRODUCT = "/api/products/PHASE3-INVALID"
REQUESTS = 128
MIN_SUCCESS = 120
GAP = timedelta(minutes=5, seconds=2)
EXPORT_SETTLE_SECONDS = 10

PHASES = [
    ("healthy_baseline", RECOMMENDATIONS, 200, None, None),
    ("healthy_control", RECOMMENDATIONS, 200, None, None),
    ("latency_fault", RECOMMENDATIONS, 200, "frontend", "latency"),
    ("latency_recovery", RECOMMENDATIONS, 200, None, None),
    ("error_fault", UNKNOWN_PRODUCT, 500, "productcatalogservice", "errors"),
    ("error_recovery", RECOMMENDATIONS, 200, None, None),
]


def utcnow():
    return datetime.now(timezone.utc)


def stamp(value):
    return value.astimezone(timezone.utc).isoformat().replace("+00:00", "Z")


def parse_stamp(value):
    return datetime.fromisoformat(value.replace("Z", "+00:00"))


def save(path, evidence):
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(".tmp")
    temporary.write_text(json.dumps(evidence, indent=2, sort_keys=True) + "\n")
    temporary.replace(path)


def command(args, env=None):
    return subprocess.check_output(args, cwd=ROOT, env=env, text=True, stderr=subprocess.STDOUT, timeout=30)


def readiness():
    result = {}
    ingestion = os.environ.get("INCIDENTLENS_INGEST_URL", "http://127.0.0.1:18080").rstrip("/")
    for name, base in (("api", API), ("ingestion", ingestion)):
        try:
            with urllib.request.urlopen(base + "/readyz", timeout=5) as response:
                result[name] = response.status
        except Exception as exc:
            result[name] = repr(exc)
    return result


def require_ready():
    result = readiness()
    if result != {"api": 200, "ingestion": 200}:
        raise AssertionError(f"product dependencies are not ready: {result}")
    return result


def compose(args, namespace=None):
    files = ["docker", "compose", "-f", str(BASE_COMPOSE)]
    if namespace is not None:
        files += ["-f", str(OVERRIDE)]
    environment = dict(os.environ)
    if namespace is not None:
        environment["INCIDENTLENS_PHASE3_NAMESPACE"] = namespace
    return command(files + args, environment)


def cpu_limit():
    return command(["docker", "inspect", "-f", "{{.HostConfig.NanoCpus}}", "incidentlens-demo-frontend-1"]).strip()


def demo_ready():
    # Use libraries already present in the pinned recommendation image to check
    # both gRPC listeners without sending application requests or editing source.
    probe = "import grpc; [grpc.channel_ready_future(grpc.insecure_channel(a)).result(timeout=10) for a in ('127.0.0.1:9001','productcatalogservice:3550')]"
    compose(["exec", "-T", "recommendationservice", "python", "-c", probe])
    endpoint = urllib.parse.urlparse(DEMO)
    with socket.create_connection((endpoint.hostname, endpoint.port or 80), timeout=5):
        pass


def send_one(route):
    trace_id, parent_id = secrets.token_hex(16), secrets.token_hex(8)
    req = urllib.request.Request(DEMO + route, headers={"traceparent": f"00-{trace_id}-{parent_id}-01"})
    started = time.monotonic()
    try:
        with urllib.request.urlopen(req, timeout=15) as response:
            status = response.status
            response.read()
    except urllib.error.HTTPError as exc:
        status = exc.code
        exc.read()
    except Exception as exc:
        status = str(exc)
    return {"trace_id": trace_id, "status": status, "elapsed_ms": round((time.monotonic() - started) * 1000, 3)}


def clickhouse_window(namespace, end):
    start = end - timedelta(minutes=5)
    # Namespace is generated by this script and contains only ASCII hex/letters.
    sql = (
        "SELECT service_name,span_name,count(),countIf(status_code=2),"
        "quantileExact(0.95)(duration_ns) FROM spans FINAL WHERE "
        f"service_namespace='{namespace}' AND span_kind=2 AND "
        f"start_time >= fromUnixTimestamp64Nano({int(start.timestamp()*1_000_000_000)}) AND "
        f"start_time < fromUnixTimestamp64Nano({int(end.timestamp()*1_000_000_000)}) "
        "GROUP BY service_name,span_name ORDER BY service_name,span_name"
    )
    output = command([
        "docker", "compose", "-f", str(ROOT / "deploy/local/compose.yaml"),
        "exec", "-T", "clickhouse", "clickhouse-client", "--user", "default",
        "--password", "local-admin", "--database", "incidentlens", "--query", sql,
    ])
    stats = []
    for line in output.splitlines():
        service, operation, count, errors, p95 = line.split("\t")
        stats.append({"service_name": service, "operation": operation,
                      "span_count": int(count), "error_count": int(errors), "p95_duration_ns": p95})
    return stats


def check_window(phase, stats):
    frontend = next((s for s in stats if s["service_name"] == "frontend" and s["operation"] == "HTTP GET"), None)
    if frontend is None or frontend["span_count"] < 100:
        raise AssertionError(f"{phase}: fewer than 100 frontend SERVER samples: {stats}")
    if phase == "error_fault":
        catalog = next((s for s in stats if s["service_name"] == "productcatalogservice" and s["operation"].endswith("/GetProduct")), None)
        if catalog is None or catalog["span_count"] < 100 or catalog["error_count"] < 100:
            raise AssertionError(f"error phase lacked native catalog ERROR samples: {stats}")


def run():
    run_id = utcnow().strftime("%Y%m%dT%H%M%SZ") + "-" + secrets.token_hex(3)
    namespace = "incidentlens-phase3-" + run_id
    path = EVIDENCE_DIR / f"phase3-{run_id}.json"
    evidence = {
        "run_id": run_id, "namespace": namespace,
        "demo_revision": "860a35de9be667ff36788d3df09ed4a96b9290fd",
        "plan": "PHASE3_SCENARIO.md", "request_count_per_phase": REQUESTS,
        "concurrency": 4, "cpu_fault": "frontend 0.1 CPU", "phases": [], "status": "running",
        "expected": [{"phase": n, "candidate_service": s, "triggered_rule": r} for n, _, _, s, r in PHASES],
    }
    save(path, evidence)
    print(f"EVIDENCE {path}\nNAMESPACE {namespace}", flush=True)
    try:
        evidence["preflight_readiness"] = require_ready()
        save(path, evidence)
        print(compose(["up", "-d", "--force-recreate"], namespace), flush=True)
        if cpu_limit() != "0":
            raise AssertionError("frontend did not start with unlimited CPU")
        # Allow the pinned services to establish their gRPC connections.
        time.sleep(8)
        demo_ready()
        previous_end = None
        for name, route, expected_http, _, _ in PHASES:
            if previous_end is not None:
                target = previous_end + GAP
                while utcnow() < target:
                    remaining = (target - utcnow()).total_seconds()
                    time.sleep(min(30, max(0.1, remaining)))
            require_ready()
            if name == "latency_fault":
                command(["docker", "update", "--cpus", "0.1", "incidentlens-demo-frontend-1"])
                if cpu_limit() != "100000000":
                    raise AssertionError("frontend CPU fault was not applied")
            phase = {"name": name, "route": route, "expected_http": expected_http,
                     "traffic_started_at": stamp(utcnow()), "status": "running"}
            evidence["phases"].append(phase)
            save(path, evidence)
            print(f"PHASE {name} START {phase['traffic_started_at']}", flush=True)
            with concurrent.futures.ThreadPoolExecutor(max_workers=4) as pool:
                responses = list(pool.map(lambda _: send_one(route), range(REQUESTS)))
            phase["traffic_ended_at"] = stamp(utcnow())
            previous_end = parse_stamp(phase["traffic_ended_at"])
            phase["http_status_counts"] = dict(Counter(str(x["status"]) for x in responses))
            phase["requests"] = responses
            if phase["http_status_counts"].get(str(expected_http), 0) < MIN_SUCCESS:
                raise AssertionError(f"{name}: fewer than {MIN_SUCCESS} expected HTTP responses: {phase['http_status_counts']}")
            time.sleep(EXPORT_SETTLE_SECONDS)
            end = utcnow()
            phase["evaluation_end"] = stamp(end)
            phase["clickhouse_current"] = clickhouse_window(namespace, end)
            check_window(name, phase["clickhouse_current"])
            phase["status"] = "traffic_verified"
            save(path, evidence)
            print(f"PHASE {name} VERIFIED T={phase['evaluation_end']} COUNTS={phase['http_status_counts']}", flush=True)
            if name == "latency_fault":
                print(compose(["up", "-d", "--force-recreate", "--no-deps", "frontend"], namespace), flush=True)
                if cpu_limit() != "0":
                    raise AssertionError("frontend CPU limit remained after recovery")
                phase["fault_removed_at"] = stamp(utcnow())
                previous_end = parse_stamp(phase["fault_removed_at"])
                save(path, evidence)

        evidence["status"] = "traffic_complete"
        save(path, evidence)
    except BaseException as exc:
        evidence["status"] = "interrupted" if isinstance(exc, KeyboardInterrupt) else "failed"
        evidence["failure"] = repr(exc)
        evidence["failure_readiness"] = readiness()
        save(path, evidence)
        raise
    finally:
        # Recreate from the original pinned file; `docker update --cpus 0`
        # does not reliably clear Docker's NanoCpus field.
        print(compose(["up", "-d", "--force-recreate"]), flush=True)
        if cpu_limit() != "0":
            raise AssertionError("frontend CPU limit not restored")
        evidence["cleanup_frontend_nano_cpus"] = cpu_limit()
        save(path, evidence)
        print(f"RESTORED pinned Demo configuration; evidence={path}", flush=True)


def evaluate(path):
    evidence = json.loads(path.read_text())
    if evidence["status"] not in ("traffic_complete", "passed", "evaluation_failed"):
        raise AssertionError(f"traffic run is incomplete: {evidence['status']}")
    namespace = evidence["namespace"]
    phase = None
    try:
        for phase in evidence["phases"]:
            if phase["name"] == "healthy_baseline":
                continue
            params = urllib.parse.urlencode({"end": phase["evaluation_end"], "namespace": namespace})
            try:
                with urllib.request.urlopen(f"{API}/api/v1/incidents?{params}", timeout=15) as response:
                    incident = json.load(response)
            except urllib.error.HTTPError as exc:
                phase["incident_http_error"] = {"status": exc.code, "body": exc.read().decode("utf-8", errors="replace")}
                raise
            phase["incident_response"] = incident
            save(path, evidence)
            if incident.get("rule_version") != "trace-v1":
                raise AssertionError(f"{phase['name']}: unexpected rule version")
            config = incident.get("config", {})
            if config != {"min_samples": 100, "latency_ratio_milli": 2000, "latency_delta_ns": "100000000", "error_rate_bps": 500, "error_increase_bps": 500}:
                raise AssertionError(f"{phase['name']}: detector defaults changed: {config}")
            # A no-candidate control is meaningful only with sufficient real data.
            for service, operation in (("frontend", "HTTP GET"), ("productcatalogservice", "hipstershop.ProductCatalogService/GetProduct")):
                group = next((g for g in incident.get("operations", []) if g.get("service_name") == service and g.get("operation") == operation), None)
                if group is None or any(group.get(w, {}).get("span_count", 0) < 100 for w in ("baseline", "current")):
                    raise AssertionError(f"{phase['name']}: insufficient {service}/{operation} in one window: {group}")
            expected = next(p for p in evidence["expected"] if p["phase"] == phase["name"])
            candidates = incident.get("candidates", [])
            if expected["candidate_service"] is None:
                if candidates:
                    raise AssertionError(f"{phase['name']}: expected no candidate, got {candidates}")
            else:
                target = next((c for c in candidates if c.get("service_name") == expected["candidate_service"]
                              and expected["triggered_rule"] in c.get("triggered_rules", [])
                              and 1 <= c.get("service_rank", 999) <= 3), None)
                if target is None:
                    raise AssertionError(f"{phase['name']}: expected top-three {expected}, got {candidates}")
                emitted_ids = {r["trace_id"] for r in phase["requests"]}
                if not target.get("evidence") or any(e.get("trace_id") not in emitted_ids for e in target["evidence"]):
                    raise AssertionError(f"{phase['name']}: evidence is not from the known current Demo requests")
            phase["evaluation_status"] = "passed"
            save(path, evidence)
            print(f"EVALUATED {phase['name']}: {len(candidates)} candidate(s)", flush=True)
        evidence["status"] = "passed"
        evidence.pop("evaluation_failure", None)
        save(path, evidence)
    except BaseException as exc:
        evidence["status"] = "evaluation_failed"
        evidence["evaluation_failure"] = repr(exc)
        if phase is not None:
            phase["evaluation_status"] = "failed"
            phase["evaluation_failure"] = repr(exc)
        save(path, evidence)
        raise


if __name__ == "__main__":
    try:
        if len(sys.argv) == 2 and sys.argv[1] == "run":
            run()
        elif len(sys.argv) == 3 and sys.argv[1] == "evaluate":
            evaluate(Path(sys.argv[2]).resolve())
        else:
            raise SystemExit("usage: phase3_scenario.py run | evaluate <evidence.json>")
    except Exception as exc:
        print(f"FAIL: {exc}", file=sys.stderr, flush=True)
        sys.exit(1)
